apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "temren.fullname" . }}-config
  labels:
    {{- include "temren.labels" . | nindent 4 }}
data:
  PORT: "8080"
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  FRONTEND_URL: {{ .Values.config.frontendUrl | quote }}
  JWT_EXPIRY: {{ .Values.config.jwtExpiry | quote }}
  SCAN_TIMEOUT: {{ .Values.config.scanTimeout | quote }}
  WORKER_CONCURRENCY: {{ .Values.config.workerConcurrency | quote }}
{{- if .Values.config.wsRedis }}
  TEMREN_WS_REDIS: {{ include "temren.wsRedisAddr" . | quote }}
  TEMREN_WS_REDIS_CHANNEL: {{ .Values.config.wsRedisChannel | quote }}
{{- end }}
