{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "temren.fullname" . }}-api
  labels:
    {{- include "temren.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.api.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.api.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.api.ingress.host | quote }}
      secretName: {{ .Values.api.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.api.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path }}
            pathType: {{ .Values.api.ingress.pathType }}
            backend:
              service:
                name: {{ include "temren.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
